name: Hostinger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'hostinger'
        type: choice
        options:
          - hostinger
          - github

jobs:
  web-deploy:
    name: 🎉 Deploy to Hostinger
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'hostinger' || github.event.inputs.environment == ''
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Build node
        run: npm install

      - name: Build for Hostinger
        run: npm run build
        env:
          DEPLOY_TARGET: hostinger

      - name: Prepare files
        run: |
          mkdir leo-portifolio
          cp docker-compose.yml leo-portifolio/
          cp nginx.conf leo-portifolio/
          cp -r dist leo-portifolio/dist

      - name: Copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: "./leo-portifolio"
          target: "/root"
          overwrite: true

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd leo-portifolio
            docker compose up -d --build
