# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches: [main]

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      # - name: Trigger GitPage Workflow
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: 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
      #     repository: https://github.com/LeonardoVieiraGuimaraes/leo-portifolio
      #     event-type: start-gitpage

      - name: Trigger Hostinger Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 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
          repository: https://github.com/LeonardoVieiraGuimaraes/leo-portifolio
          event-type: start-hostinger
