name: Upload via SFTP

on:
  push:
    branches:
      - main # substitua com o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install openssh-client -y

      - name: Upload via SFTP
        run: scp -r /dist/*  root@191.101.78.233:/leo_portifolio
        # Substitua '/path/to/your/folder' com o caminho para a sua pasta local
        # Substitua 'user' com seu nome de usuário SFTP
        # Substitua 'your_sftp_host' com o host do seu servidor SFTP
        # Substitua '/remote/path' com o caminho remoto onde você deseja enviar a pasta
